version: '2'

services:

  lb:
    image: rancher/lb-service-haproxy:v0.6.2
    ports:
    - 80:80/tcp
    - 443:443/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.global: 'true'

  http-https-redirect:
    image: nhsuk/docker-nginx-https-redirect:1.0.0
    labels:
      io.rancher.scheduler.global: 'true'
