version: '2'

catalog:
  name: nhsuk_c2s_lb
  version: 1.0.1
  description: |
    Connecting to Services - Load Balancer config for staging/production
  minimum_rancher_version: v0.59.0
  questions:
    - variable: "pharmacy_finder_frontend_service"
      description: "The pharmacy finder 'stack/service' which the load balancer will route to"
      label: "Stack:"
      required: true
      default: "c2s-pharmacy-finder/c2s-frontend"
      type: "string"
    - variable: "profiles_frontend_service"
      description: "The profiles 'stack/service' which the load balancer will route to"
      label: "Stack:"
      required: true
      default: "c2s-profiles/profiles-frontend"
      type: "string"
    - variable: "gp_finder_frontend_service"
      description: "The GP Finder 'stack/service' which the load balancer will route to"
      label: "Stack:"
      required: true
      default: "c2s-gp-finder/gp-finder-frontend"
      type: "string"

services:
  http-https-redirect:
    start_on_create: true

  lb:
    start_on_create: true
    lb_config:
      certs: []
      default_cert: c2s
      port_rules:
      - hostname: ''
        priority: 1
        protocol: http
        service: http-https-redirect
        source_port: 80
        target_port: 80
      - hostname: ''
        path: /finders
        priority: 2
        protocol: https
        service: ${pharmacy_finder_frontend_service}
        source_port: 443
        target_port: 3000
      - hostname: ''
        path: /gp-surgeries
        priority: 3
        protocol: https
        service: ${profiles_frontend_service}
        source_port: 443
        target_port: 3000
      - hostname: ''
        path: /gp-finder
        priority: 4
        protocol: https
        service: ${gp_finder_frontend_service}
        source_port: 443
        target_port: 3000
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
