name: C2S - Load Balancer
description: |
  Connecting to Services - Load Balancer config for staging/production
version: v1
category: nhsuk beta
projectURL: https://github.com/nhsuk/nhsuk-rancher-templates
