name: C2S - Profiles
description: |
  Connecting to Services - Profiles (requires separate loadbalancer stack or traefik lb running in the stack)
version: v1
category: nhsuk beta profiles
projectURL: https://github.com/nhsuk/profiles
