name: C2S - Profiles
description: |
  Connecting to Services - Profiles (requires separate loadbalancer stack or traefik lb running in the stack)
version: 1.0.0
category: nhsuk beta profiles
projectURL: https://github.com/nhsuk/profiles
