version: '2'

services:
  wagtail:
    image: nhsuk/content-platform:${CONTENT_PLATFORM_DOCKER_IMAGE_TAG}
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_PORT: 1433
      SA_USER: ${SA_USER}
      SA_PASS: ${SA_PASS}
      WAGTAIL_SU_EMAIL: ${WAGTAIL_SU_EMAIL}
      WAGTAIL_SU_USER: ${WAGTAIL_SU_USER}
      WAGTAIL_SU_PASS: ${WAGTAIL_SU_PASS}
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
      SECRET_KEY: ${SECRET_KEY}
    labels:
      traefik.enable: stack
      traefik.domain: ${TRAEFIK_DOMAIN}
      traefik.port: 8000
