version: '2'

catalog:
  name: nhsuk_profiles
  version: 1.1.1
  description: |
    Connecting to Services - Profiles
  minimum_rancher_version: v0.59.0
  questions:
    - variable: "PROFILES_DOCKER_IMAGE_TAG"
      description: "profiles Docker image tag"
      label: "profiles Docker image tag:"
      required: true
      default: "latest"
      type: "string"
    - variable: "PROFILES_DB_DOCKER_IMAGE_TAG"
      description: "profiles-db Docker image tag"
      label: "profiles-db Docker image tag:"
      required: true
      default: "latest"
      type: "string"
    - variable: "TRAEFIK_DOMAIN"
      description: "Traefik domain suffix"
      label: "traefik domain suffix:"
      required: true
      default: "dev.beta.nhschoices.net"
      type: "string"
    - variable: "HOTJAR_ID"
      description: "HotJar Tracking ID"
      label: "HotJar Tracking ID:"
      required: true
      default: "265857"
      type: "string"
    - variable: "GOOGLE_ID"
      description: "Google Tracking ID"
      label: "Google Tracking ID:"
      required: true
      default: "UA-67365892-5"
      type: "string"
    - variable: "WEBTRENDS_ID"
      description: "WebTrends ID"
      label: "WebTrends ID:"
      required: true
      default: "dcs222rfg0jh2hpdaqwc2gmki_9r4q"
      type: "string"

services:
  profiles-frontend:
    scale: 1
    start_on_create: true
    health_check:
      response_timeout: 5000
      healthy_threshold: 2
      port: 3000
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 5000
      strategy: recreate
      request_line: GET "/" "HTTP/1.0"
      reinitializing_timeout: 60000

  profiles-db:
    scale: 1
    start_on_create: true
    health_check:
      response_timeout: 60000
      healthy_threshold: 2
      port: 27017
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 20000
      strategy: recreate
      request_line: ''
      reinitializing_timeout: 60000
