version: '2'

services:

  lb:
    image: rancher/lb-service-haproxy:v0.4.9
    ports:
    - 80:80/tcp
    - 443:443/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.global: 'true'

  http-https-redirect:
    image: jamessharp/docker-nginx-https-redirect
    labels:
      io.rancher.scheduler.global: 'true'
