version: '2'

catalog:
  name: nhsuk_gp-redirect
  version: 1.0.0
  description: |
    GP Redirect - forwards requests onto appropriate page on profiles site
  minimum_rancher_version: v0.59.0
  questions:
    - variable: "GP_REDIRECT_DOCKER_IMAGE_TAG"
      description: "gp-redirect Docker image tag"
      label: "gp-redirect Docker image tag:"
      required: true
      default: "latest"
    - variable: "TRAEFIK_DOMAIN"
      description: "Traefik domain suffix"
      label: "traefik domain suffix:"
      required: true
      default: "dev.c2s.nhschoices.net"
      type: "string"

services:
  gp-redirect:
    scale: 1
    start_on_create: true
    health_check:
      response_timeout: 5000
      healthy_threshold: 2
      port: 3000
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 5000
      strategy: recreate
      request_line: GET "/" "HTTP/1.0"
      reinitializing_timeout: 60000
