version: '2'

services:
  c2s-frontend:
    image: "nhsuk/connecting-to-services:${c2s_docker_image_tag}"
    environment:
      NODE_ENV: production
      SPLUNK_HEC_ENDPOINT: ${splunk_hec_endpoint}
      SPLUNK_HEC_TOKEN: ${splunk_hec_token}
      HOTJAR_ANALYTICS_TRACKING_ID: ${hotjar_id}
      GOOGLE_ANALYTICS_TRACKING_ID: ${google_id}
      WEBTRENDS_ANALYTICS_TRACKING_ID: ${webtrends_id}
      API_BASE_URL: 'http://nearby-services-api:3001'
    links:
    - nearby-services-api:nearby-services-api

  lb:
    image: rancher/lb-service-haproxy:v0.4.9
    ports:
    - 80:80/tcp
    - 443:443/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.global: 'true'

  nearby-services-api:
    image: "nhsuk/nearby-services-api:${nearbyservices_docker_image_tag}"
    environment:
      NODE_ENV: production
      SPLUNK_HEC_ENDPOINT: ${splunk_hec_endpoint}
      SPLUNK_HEC_TOKEN: ${splunk_hec_token}

