version: '2'

services:
  bth:
    image: nhsuk/bth-wagtail:${BTH_DOCKER_IMAGE_TAG}
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_PORT: 1433
      SA_USER: ${SA_USER}
      SA_PASSWORD: ${SA_PASSWORD}
      DB_EMAIL: ${DB_EMAIL}
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
      SECRET_KEY: ${SECRET_KEY}
    labels:
      traefik.enable: stack
      traefik.domain: ${TRAEFIK_DOMAIN}
      traefik.port: 8000
