version: '2'

services:

  c2s-frontend:
    image: "nhsuk/connecting-to-services:${c2s_docker_image_tag}"
    environment:
      NODE_ENV: production
      SPLUNK_HEC_ENDPOINT: ${splunk_hec_endpoint}
      SPLUNK_HEC_TOKEN: ${splunk_hec_token}
      HOTJAR_ANALYTICS_TRACKING_ID: ${hotjar_id}
      GOOGLE_ANALYTICS_TRACKING_ID: ${google_id}
      WEBTRENDS_ANALYTICS_TRACKING_ID: ${webtrends_id}
      API_BASE_URL: 'http://nearby-services-api:3001'
    labels:
      traefik.enable: true
      traefik.domain: ${traefik_domain}
      traefik.port: 3000
      traefik.alias: ${traefik_alias}
      io.rancher.container.pull_image: always
    links:
    - nearby-services-api:nearby-services-api

  nearby-services-api:
    image: "nhsuk/nearby-services-api:${nearbyservices_docker_image_tag}"
    links:
    environment:
      NODE_ENV: production
      SPLUNK_HEC_ENDPOINT: ${splunk_hec_endpoint}
      SPLUNK_HEC_TOKEN: ${splunk_hec_token}
    labels:
      io.rancher.container.pull_image: always
