name: C2S - Pharmacy Finder
description: |
  Connecting to Services - Pharmacy Finder (require separate loadbalancer stack or traefik lb running in the stack)
version: v1
category: nhsuk beta
projectURL: https://github.com/nhsuk/nhsuk-rancher-templates
